'''
    Description: game dic for f
'''
f_game_dic_all=[
    'Pokemon',
    'Gliding',
    'Parachuting',
    'RollerCoaster',
    'Skiing',
    'CS',
    'Dota2',
    'GalaxyOnFire',
    'LOL',
    'MC',
    'BTSRun',
    # 'Graffiti',
    # 'KasabianLive',
    # 'LetsNotBeAloneTonight',
    # 'Antarctic',
    # 'BlueWorld',
    # 'Dubai',
    # 'Egypt',
    # 'StarryPolar',
    # 'A380',
    # 'CandyCarnival',
    # 'MercedesBenz',
    # 'RingMan',
    # 'RioOlympics',
    # 'Help',
    # 'IRobot',
    # 'Predator',
    # 'ProjectSoul',
    # 'AirShow',
    # 'DrivingInAlps',
    # 'F5Fighter',
    # 'HondaF1',
    # 'Rally',
    # 'AcerPredator',
    # 'BFG',
    # 'CMLauncher',
    # 'Cryogenian',
]
f_game_dic_new_all=[
    'A380',
    'AcerEngine',
    'AcerPredator',
    'AirShow',
    'BFG',
    'Bicycle',
    'BlueWorld',
    'BTSRun',
    'Camping',
    'CandyCarnival',
    'Castle',
    'Catwalks',
    'CMLauncher',
    'CMLauncher2',
    'CS',
    'DanceInTurn',
    'Dancing',
    'DrivingInAlps',
    'Egypt',
    'F5Fighter',
    'Flight',
    'GalaxyOnFire',
    'Graffiti',
    'GTA',
    'Guitar',
    'HondaF1',
    'InsideCar',
    'IRobot',
    'KasabianLive',
    'KingKong',
    'Lion',
    'LoopUniverse',
    'Manhattan',
    'MC',
    'MercedesBenz',
    'Motorbike',
    'Murder',
    'Let\'sNotBeAloneTonight',
    'Orion',
    'Parachuting',
    'Parasailing',
    'Pearl',
    'Predator',
    'ProjectSoul',
    'Rally',
    'RingMan',
    'RioOlympics',
    'Roma',
    'Shark',
    'Skiing',
    'Snowfield',
    'SnowRopeway',
    'SpaceWar',
    'SpaceWar2',
    'Square',
    'StarryPolar',
    'StarWars',
    'StarWars2',
    'Stratosphere',
    'StreetFighter',
    'Sunset',
    'Supercar',
    'SuperMario64',
    'Surfing',
    'SurfingArctic',
    'Symphony',
    'TalkingInCar',
    'Terminator',
    'TheInvisible',
    'Village',
    'VRBasketball',
    'WaitingForLove',
    'Waterfall',
    'Waterskiing',
    'WesternSichuan',
    'Yacht',
]
f_game_dic_new_test=[
    'BlueWorld',
    'BTSRun',
    'CMLauncher2',
    'Dancing',
    'Guitar',
    'InsideCar',
    'KingKong',
    'SpaceWar',
    'SpaceWar2',
    'Sunset',
    'Symphony',
    'WaitingForLove',
    'Waterfall',
    'StarryPolar',
    'RioOlympics'
]
