f_game_dic_new_train=[
    'A380',
    'AcerEngine',
    # 'AcerPredator',
    # 'AirShow',
    # 'BFG',
    # 'Bicycle',
    # 'Camping',
    # 'CandyCarnival',
    # 'Castle',
    # 'Catwalks',
    # 'CMLauncher',
    # 'CS',
    # 'DanceInTurn',
    # 'DrivingInAlps',
    # 'Egypt',
    # 'F5Fighter',
    # 'Flight',
    # 'GalaxyOnFire',
    # 'Graffiti',
    # 'GTA',
    # 'HondaF1',
    # 'IRobot',
    # 'KasabianLive',
    # 'Lion',
    # 'LoopUniverse',
    # 'Manhattan',
    # 'MC',
    # 'MercedesBenz',
    # 'Motorbike',
    # 'Murder',
    # 'Orion',
    # 'Parachuting',
    # 'Parasailing',
    # 'Pearl',
    # 'Predator',
    # 'ProjectSoul',
    # 'Rally',
    # 'RingMan',
    # 'Roma',
    # 'Shark',
    # 'Skiing',
    # 'Snowfield',
    # 'SnowRopeway',
    # 'Square',
    # 'StarWars',
    # 'StarWars2',
    # 'Stratosphere',
    # 'StreetFighter',
    # 'Supercar',
    # 'SuperMario64',
    # 'Surfing',
    # 'SurfingArctic',
    # 'TalkingInCar',
    # 'Terminator',
    # 'TheInvisible',
    # 'Village',
    # 'VRBasketball',
    # 'Waterskiing',
    # 'WesternSichuan',
    # 'Yacht',
]

f_game_dic_new_test = [
    'WaitingForLove',
    'SpaceWar',
    'KingKong',
    'SpaceWar2',
    'Guitar',
    'BTSRun',
    'CMLauncher2',
    'Symphony',
    'RioOlympics',
    'Dancing',
    'StarryPolar',
    'InsideCar',
    'Sunset',
    'Waterfall',
    'BlueWorld'
]

f_game_dic_new_test_parallel = [f_game_dic_new_test[3]] * 20


f_game_dic_all=[
    'Pokemon',
    'Gliding',
    'Parachuting',
    'RollerCoaster',
    'Skiing',
    'CS',
    'Dota2',
    'GalaxyOnFire',
    'LOL',
    'MC',
    'BTSRun',
]
